### ISSUE TITLE
SeasonHUD v1.10.0 and v1.10.1 crashes for 1.21

### ISSUE THREAD

**Issue by Professor-Puddle** [IanMods/SeasonHUD#110]
**Describe the issue**

In Modrinth, versions 1.10.0 and 1.10.1 are listed to work for 1.21 and 1.21.1, however when I update the mod in my 1.21 instance, it crashes, saying that the mod is for 1.21.1 and not for 1.21.

![image](https://github.com/user-attachments/assets/be56bcc9-8f26-4b10-8fb1-7de54e0bb425)

**Minecraft Version**

1.21

**Mod Version**

versions 1.10.0 and 1.10.1

**Modloader(Fabric/Forge/NeoForge)**

Fabric

**Modloader Version**

0.16.3

**Additional Info (Crashlog/Modlist)**

![image](https://github.com/user-attachments/assets/0aa61966-c1e4-4d13-87c9-79939b94bee3)

**Comment by lanAnderson** [comment]
This should be fixed in 1.10.2, once I test and upload it
